### ISSUE TITLE
Allow marking of custom types with an attribute to consider them "Task types".

### ISSUE THREAD

**Issue by miniBill** [asizikov/AsyncSuffix#2]
Allow marking of custom types with an attribute to consider them "Task types".

From what I observed it should be enough to add an `|| type.HasAnAttributeThatSaysSo()` to https://github.com/asizikov/AsyncSuffix/blob/master/AsyncSuffix/Analyzer/TaskExtensions.cs#L9. Admittedly, I would not know how to implement that method.

**Comment by asizikov** [comment]
Sounds interesting.
Could you please give me more details? What are you trying to achieve? I might consider another solution for that.

**Comment by miniBill** [comment]
I've got a custom `IAsyncEnumerable<T>` class and I would like all the methods returning that type to be named `FooAsync` too.

**Comment by asizikov** [comment]
Yup, I guess it makes sense. 
I like this idea, thanks.

**Comment by asizikov** [comment]
@miniBill well, it took me some time, but I have a working prototype:

![custom async types](https://cloud.githubusercontent.com/assets/819053/11460947/baace582-96f8-11e5-9179-ab5b6840ac37.png)

**Comment by miniBill** [comment]
Cool =)

**Comment by asizikov** [comment]
@miniBill and it's published now
https://resharper-plugins.jetbrains.com/packages/Sizikov.AsyncSuffix/1.2.0
Give it a try and let me know how it works for you.
