### ISSUE TITLE
ReSharper 2016.2 ignores this extension

### ISSUE THREAD

**Issue by imanushin** [asizikov/AsyncSuffix#38]
![image](https://cloud.githubusercontent.com/assets/4425474/16909915/1636a30c-4cde-11e6-90b5-e878aa38182d.png)

Async Suffix package does not have ReSharper 2016.2 support (the newest version).

**Comment by asizikov** [comment]
Yep, it's time to update.

Thanks.

**Comment by asizikov** [comment]
<img width="1043" alt="screen shot 2016-07-18 at 11 12 50" src="https://cloud.githubusercontent.com/assets/819053/16910403/b84842aa-4cd8-11e6-8fec-b8738142f8a1.png">

And for now, you can use a pre-release version of the package. There is an annoying UI glitch there, but the fix is on the way.

**Comment by asizikov** [comment]
@imanushin there is a stable release for ReSharper 2016.2
