### ISSUE TITLE
Remove commas in tags in nuspec

### ISSUE THREAD

**Issue by zvirja** [asizikov/AsyncSuffix#43]
For `.nuspec` tags space is a valid tag delimiter. However, you arranged commas:

``` xml
<tags>async method, naming, task</tags>
```

As result, they are parsed incorrectly:
![image](https://cloud.githubusercontent.com/assets/1074182/19434323/63a59202-946d-11e6-8125-7a95eda461ed.png)

**Comment by asizikov** [comment]
Nice catch, thanks!
