### ISSUE TITLE
ReSharper 2016.3.1 support

### ISSUE THREAD

**Issue by VladimirTyrin** [asizikov/AsyncSuffix#48]
ReSharper has been updated recently and now ignores AsyncSuffix (no suggestions at all :( )

**Comment by asizikov** [comment]
What is the version of the plugin you have installed?

**Comment by VladimirTyrin** [comment]
@asizikov it started to work! Sorry for false report!

Maybe still be useful (plugin started to work in 10 minutes or so)

AsyncSuffix 2016.3
ReSharper 2016.3.1
